
export const GET_ALL_CANDIDATES_SUCCESS = "GET_ALL_APPOINTMENT_SUCCESS"
export const GET_ALL_CANDIDATES_FAILED = "GET_ALL_APPOINTMENT_FAILED"
export const GET_ALL_CANDIDATES_LOADING = "GET_ALL_APPOINTMENT_LOADING"

